feat(data_connector): Adding support to YouTube search API
sfu-db/DataConnectorConfigs pull request #17
Opened 2020-06-28 08:05 UTC by pallavibharadwaj

Related to #117
This supports the YouTube Search API where the users can search for three types of items - videos, channels, and playlists with an optional parameter `type` and a mandatory string matching parameter `q` to search for relevant information.

Ex: `dc.query("videos", q="surfing", part="snippet", type='video')`

2020-06-28 08:08 UTC, pallavibharadwaj commented
@dovahcrow and @peiwangdb - request to review this PR. Thank you!

2020-06-28 22:00 UTC, peiwangdb requested changes
Thanks @pallavibharadwaj !
1. Pagination part is missing. I saw in the documentation(https://developers.google.com/youtube/v3/docs/search/list) of youtube API, optional parameter maxResults and pageToken might be related to the pagination. This part is missing in videos.json. Is it possible to add it?
2. The CI test did not pass.

2020-07-01 23:08 UTC, pallavibharadwaj commented
> Pagination part is missing. I saw in the documentation(https://developers.google.com/youtube/v3/docs/search/list) of youtube API, optional parameter maxResults and pageToken might be related to the pagination. This part is missing in videos.json. Is it possible to add it?

@peiwangdb - My understanding is that DC's pagination parameters act as a wrapper around `maxResults` and `pageToken` provided by YouTube, in order to achieve uniformity across websites. That is why I didn't include them. Please correct me if I'm wrong.

2020-07-02 00:02 UTC, peiwangdb commented
> My understanding is that DC's pagination parameters act as a wrapper around `maxResults` and `pageToken` provided by YouTube, in order to achieve uniformity across websites. That is why I didn't include them. Please correct me if I'm wrong.

Yes, DC's pagination parameters act as a wrapper. But we need to define how the pagination will work.
Currently, we support two pagination schemes: limit(yelp) and cursor(twitter)
Please refer to how to write:
code: https://github.com/sfu-db/dataprep/blob/develop/dataprep/data_connector/connector.py (ctrl+f limit)
examples:
https://github.com/sfu-db/DataConnectorConfigs/blob/master/yelp/businesses.json
https://github.com/sfu-db/DataConnectorConfigs/blob/master/twitter/tweets.json
So you need to first identify if the youtube pagination follows one of the schemes defined, and then add a pagination block.

> About the tests failing for YouTube support - it says `ERROR: file not found: ./youtube/tests/*`
> What kind of tests should I be adding to this folder? I do not see any other website folders including a tests folder to take reference from.

I guess you just need to manually add a folder and a test file just like this: https://github.com/sfu-db/DataConnectorConfigs/tree/master/twitter/tests https://github.com/sfu-db/DataConnectorConfigs/tree/master/dblp/tests

2020-07-04 01:23 UTC, pallavibharadwaj commented
@peiwangdb - Made both the changes you suggested. 
As discussed, `pageToken` cursor type pagination is not supported yet with DC since `nextPageToken` and `prevPageToken` are outside the list items extracted within the connector. Thus I've included only maxRequests as of now. Thank you.

2020-07-07 17:49 UTC, merged