feat(connector): Config file changes to support universal parameter _…
sfu-db/DataConnectorConfigs pull request #31
Opened 2020-09-23 06:50 UTC by pallavibharadwaj

Config file changes related to [feat(data_connector): full text search _q to be a universal parameter #356](https://github.com/sfu-db/dataprep/pull/356/commits/9407cf565e347fe3574a9240602b48256220d1d5) of dataprep.

Ex: 
For Yelp, "term" is used as the search key and "q" for the rest of the websites so far. This would now be "_q" for all websites so the user doesn't have to worry about the difference in nomenclature.
`"search": {
        "search_key": "term"
}`

2020-09-23 07:17 UTC, pallavibharadwaj commented
The failing test cases will pass once [the related dataprep PR](https://github.com/sfu-db/dataprep/pull/356) is merged.

2020-09-30 06:23 UTC, pallavibharadwaj commented
@peiwangdb @dovahcrow Please take a look at the updated config file changes related to [https://github.com/sfu-db/dataprep/pull/375](#375). 
1. The `term` parameter of yelp is retained so that both `term` and `_q `can be used.
2. The other websites have "q" itself as their parameter, so I have removed them to avoid redundancy.
3. Some of the config file `tests/tests.py` had the old connector path and were failing - I have updated that as well.

2020-09-30 16:49 UTC, dovahcrow requested changes
@pallavibharadwaj Thanks for the fixes! Overall it looks good. I left some comments about the removing of parameter `q` and naming issue.

2020-09-30 16:49 UTC, dovahcrow commented on dblp/publication.json
> -            "q": false,
Why this is removed?

2020-09-30 16:49 UTC, dovahcrow commented on dblp/publication.json
> +            "search_key": "q"
Here I think we've already renamed `search_key` to `key`

2020-09-30 16:49 UTC, dovahcrow commented on yelp/businesses.json
> +            "term": false,
No need to make it false. I've changed the parameter verification logic.

2020-10-04 09:53 UTC, pallavibharadwaj commented
> Thanks for the fixes! Overall it looks good. I left some comments about the removing of parameter `q` and naming issue.

Thanks, @dovahcrow. Fixed them, please take a look!

2020-10-04 22:44 UTC, dovahcrow approved these changes

2020-10-04 22:44 UTC, dovahcrow commented
Great! Thanks @pallavibharadwaj !

2020-10-04 22:44 UTC, merged